{% set name = "ttags" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/npezza93/{{ name }}/archive/{{ version }}.tar.gz
  sha256: da8681a25122543d25362eb91a3be610f86e7bd6e0a0da6947511a59762c4325

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - ttags --help

about:
  home: https://github.com/npezza93/ttags
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Generate ctags using Tree Sitter
  dev_url: https://github.com/npezza93/ttags

extra:
  recipe-maintainers:
    - danielnachun
